universe = vanilla
executable = /home/kkacanja/ecc_pe/gw170817/seob/run.sh
getenv = True
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

output =  /home/kkacanja/ecc_pe/gw170817/logs/0.3e_seob_gw170817.out
error =  /home/kkacanja/ecc_pe/gw170817/logs/0.3e_seob_gw170817.err
log =  /home/kkacanja/ecc_pe/gw170817/logs/0.3e_seob_gw170817.log

# Request resources
request_memory = 30 GB
request_cpus = 64

batch_name = 0.3e_seob_gw170817
# Queue the job
queue


