universe = vanilla
executable = /home/kkacanja/ecc_gw190817/pe/gw190814/teob/0.3ecc_teob_sampling_full.sh
getenv = True
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

output =  /home/kkacanja/ecc_gw190817/pe/gw190814/logs/0.3ecc_teob_sampling_full.out
error =  /home/kkacanja/ecc_gw190817/pe/gw190814/logs/0.3ecc_teob_sampling_full.err
log =  /home/kkacanja/ecc_gw190817/pe/gw190814/logs/0.3ecc_teob_sampling_full.log

# Request resources
request_memory = 30 GB
request_cpus = 64

batch_name = 0.3ecc_teob_sampling_full
# Queue the job
queue


