universe = vanilla
executable = /home/kkacanja/ecc_pe/gw190814/teob/run.sh
getenv = True
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

output =  /home/kkacanja/ecc_pe/gw190814/logs/teob_gw190814_HM.out
error =  /home/kkacanja/ecc_pe/gw190814/logs/teob_gw190814_HM.err
log =  /home/kkacanja/ecc_pe/gw190814/logs/teob_gw190814_HM.log

# Request resources
request_memory = 30 GB
request_cpus = 64

batch_name = teob_gw190814_HM
# Queue the job
queue


