universe = vanilla
executable = /home/kkacanja/ecc_pe/gw200105/teobprecc/run.sh
getenv = True
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

output =  /home/kkacanja/ecc_pe/gw200105/logs/teobprecc_gw200105.out
error =  /home/kkacanja/ecc_pe/gw200105/logs/teobprecc_gw200105.err
log =  /home/kkacanja/ecc_pe/gw200105/logs/teobprecc_gw200105.log

# Request resources
request_memory = 50 GB
request_cpus = 64

batch_name = teobprecc_gw200105
# Queue the job
queue


