universe = vanilla
executable = /home/kkacanja/ecc_pe/new/gw230529/teob/run.sh
getenv = True
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

output =  /home/kkacanja/ecc_pe/new/gw230529/logs/teob_gw230529_2.out
error =  /home/kkacanja/ecc_pe/new/gw230529/logs/teob_gw230529_2.err
log =  /home/kkacanja/ecc_pe/new/gw230529/logs/teob_gw230529_2.log

# Request resources
request_memory = 30 GB
request_cpus = 64

batch_name = teob_gw230529
# Queue the job
queue


