universe = vanilla
executable = /home/kkacanja/ecc_pe/new/gw190425/seobHM/run.sh
getenv = True
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

output =  /home/kkacanja/ecc_pe/new/gw190425/logs/seobHM_gw190425.out
error =  /home/kkacanja/ecc_pe/new/gw190425/logs/seobHM_gw190425.err
log =  /home/kkacanja/ecc_pe/new/gw190425/logs/seobHM_gw190425.log

Requirements = ! regexp("u20node", TARGET.name)

# Request resources
request_memory = 10 GB
request_cpus = 64

batch_name = seobHM_gw190425
# Queue the job
queue


