universe = vanilla
executable = /home/kkacanja/ecc_gw190817/pe/seob/0.3e_seob_sampling.sh
getenv = True
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

output =  /home/kkacanja/ecc_gw190817/pe/logs/0.3e_seob_sampling.out
error =  /home/kkacanja/ecc_gw190817/pe/logs/0.3e_seob_sampling.err
log =  /home/kkacanja/ecc_gw190817/pe/logs/0.3e_seob_sampling.log

# Request resources
request_memory = 30 GB
request_cpus = 64

batch_name = 0.3e_seob_sampling
# Queue the job
queue


