universe = vanilla
executable = /home/kkacanja/ecc_pe/gw170817/seobHM/run.sh
getenv = True
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

output =  /home/kkacanja/ecc_pe/gw170817/logs/seobHM_gw170817.out
error =  /home/kkacanja/ecc_pe/gw170817/logs/seobHM_gw170817.err
log =  /home/kkacanja/ecc_pe/gw170817/logs/seobHM_gw170817.log

# Request resources
request_memory = 30 GB
request_cpus = 64

batch_name = seobHM_gw170817
# Queue the job
queue


