universe = vanilla
executable = /home/kkacanja/ecc_pe/gw190814/seobHM/run.sh
getenv = True
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

output =  /home/kkacanja/ecc_pe/gw190814/logs/seob_gw190814_HM.out
error =  /home/kkacanja/ecc_pe/gw190814/logs/seob_gw190814_HM.err
log =  /home/kkacanja/ecc_pe/gw190814/logs/seob_gw190814_HM.log

# Request resources
request_memory = 30 GB
request_cpus = 64

batch_name = seob_gw190814_HM
# Queue the job
queue


