universe = vanilla
executable = /home/kkacanja/ecc_pe/new/gw190814/seob/run.sh
getenv = True
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

output =  /home/kkacanja/ecc_pe/new/gw190814/logs/seob_gw190814.out
error =  /home/kkacanja/ecc_pe/new/gw190814/logs/seob_gw190814.err
log =  /home/kkacanja/ecc_pe/new/gw190814/logs/seob_gw190814.log

# Request resources
request_memory = 10 GB
request_cpus = 64
#Requirements = ! regexp("u20node", TARGET.name)

batch_name = seob_gw190814
# Queue the job
queue


