universe = vanilla
executable = /home/kkacanja/ecc_pe/new/gw170817/seob/run.sh
getenv = True
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

output =  /home/kkacanja/ecc_pe/new/gw170817/logs/seob_gw170817.out
error =  /home/kkacanja/ecc_pe/new/gw170817/logs/seob_gw170817.err
log =  /home/kkacanja/ecc_pe/new/gw170817/logs/seob_gw170817.log

# Request resources
request_memory = 70 GB
request_cpus = 64

batch_name = seob_gw170817
# Queue the job
queue


