universe = vanilla
executable = /home/kkacanja/ecc_pe/gw170817/teobHM/run.sh
getenv = True
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

output =  /home/kkacanja/ecc_pe/gw170817/logs/teobHM_gw170817.out
error =  /home/kkacanja/ecc_pe/gw170817/logs/teobHM_gw170817.err
log =  /home/kkacanja/ecc_pe/gw170817/logs/teobHM_gw170817.log

request_memory = 30 GB
request_cpus = 64

batch_name = teobHM_gw170817

queue


