universe = vanilla
executable = /home/kkacanja/ecc_gw190817/pe/gw230529/seob/0.3e_seob_sampling.sh
getenv = True
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

output =  /home/kkacanja/ecc_gw190817/pe/gw230529/logs/0.3e_seob_gw230529.out
error =  /home/kkacanja/ecc_gw190817/pe/gw230529/logs/0.3e_seob_gw230529.err
log =  /home/kkacanja/ecc_gw190817/pe/gw230529/logs/0.3e_seob_gw230529.log

# Request resources
request_memory = 30 GB
request_cpus = 64

batch_name = 0.3e_seob_gw230529
# Queue the job
queue


