universe = vanilla
executable = /home/kkacanja/ecc_pe/gw190425/seob/run.sh
getenv = True
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

output =  /home/kkacanja/ecc_pe/gw190425/logs/seob_gw190425.out
error =  /home/kkacanja/ecc_pe/gw190425/logs/seob_gw190425.err
log =  /home/kkacanja/ecc_pe/gw190425/logs/seob_gw190425.log

request_memory = 70 GB
request_cpus = 64

batch_name = seob_gw190425
queue


