universe = vanilla
executable = /home/kkacanja/ecc_pe/gw190425/teobHM/run.sh
getenv = True
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

output =  /home/kkacanja/ecc_pe/gw190425/logs/teobHM_gw190425.out
error =  /home/kkacanja/ecc_pe/gw190425/logs/teobHM_gw190425.err
log =  /home/kkacanja/ecc_pe/gw190425/logs/teobHM_gw190425.log

request_memory = 30 GB
request_cpus = 64

batch_name = teobHM_gw190425

queue


