universe = vanilla
executable = /home/kkacanja/ecc_pe/gw170817/teob/run.sh
getenv = True
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

output =  /home/kkacanja/ecc_pe/gw170817/logs/teob_gw170817.out
error =  /home/kkacanja/ecc_pe/gw170817/logs/teob_gw170817.err
log =  /home/kkacanja/ecc_pe/gw170817/logs/teob_gw170817.log

request_memory = 70 GB
request_cpus = 64

batch_name = teob_gw170817

queue


