universe = vanilla
executable = /home/kkacanja/ecc_pe/new/gw200115/teobHM/run.sh
getenv = True
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

output =  /home/kkacanja/ecc_pe/new/gw200115/logs/teobHM_gw200115.out
error =  /home/kkacanja/ecc_pe/new/gw200115/logs/teobHM_gw200115.err
log =  /home/kkacanja/ecc_pe/new/gw200115/logs/teobHM_gw200115.log

# Request resource
Requirements = ! regexp("u20node", TARGET.name)

request_memory = 10 GB
request_cpus = 64

batch_name = teobHM_gw200115
# Queue the job
queue


