universe = vanilla
executable = /home/kkacanja/ecc_pe/gw200105/teob/0.3/no_marg/new_run/check_stats.sh
getenv = True
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

output =  /home/kkacanja/ecc_pe/gw200105/logs/teob_gw200105_no_marg_stats.out
error =  /home/kkacanja/ecc_pe/gw200105/logs/teob_gw200105_no_marg_stats.err
log =  /home/kkacanja/ecc_pe/gw200105/logs/teob_gw200105_no_marg_stats.log

# Request resources
request_memory = 10 GB
request_cpus = 1

batch_name = gw200105_nomarg_stats_check
# Queue the job
queue


