universe = vanilla
executable = /home/kkacanja/ecc_pe/gw200105/teob/0.3/no_marg/new_run/run.sh
getenv = True
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

output =  /home/kkacanja/ecc_pe/gw200105/logs/teob_0.3ecc_gw200105_no_marg.out
error =  /home/kkacanja/ecc_pe/gw200105/logs/teob_0.3ecc_gw200105_no_marg.err
log =  /home/kkacanja/ecc_pe/gw200105/logs/teob_0.3ecc_gw200105_no_marg.log

# Request resources
request_memory = 50 GB
request_cpus = 64

batch_name = teob_0.3ecc_gw200105_nomarg_n
# Queue the job
queue


