universe = vanilla
executable = /home/kkacanja/ecc_pe/gw190814/teobprecc/run.sh
getenv = True
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

output =  /home/kkacanja/ecc_pe/gw190814/logs/teob_gw190814_HM_precc.out
error =  /home/kkacanja/ecc_pe/gw190814/logs/teob_gw190814_HM_precc.err
log =  /home/kkacanja/ecc_pe/gw190814/logs/teob_gw190814_HM_precc.log

# Request resources
request_memory = 30 GB
request_cpus = 64

batch_name = teob_gw190814_HM_precc
# Queue the job
queue


