universe = vanilla
executable = /home/kkacanja/ecc_gw190817/pe/gw200105/seob/0.3e_seob_sampling.sh
getenv = True
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

output =  /home/kkacanja/ecc_gw190817/pe/gw200105/logs/0.3e_seob_gw200105.out
error =  /home/kkacanja/ecc_gw190817/pe/gw200105/logs/0.3e_seob_gw200105.err
log =  /home/kkacanja/ecc_gw190817/pe/gw200105/logs/0.3e_seob_gw200105.log

# Request resources
request_memory = 30 GB
request_cpus = 64

batch_name = 0.3e_seob_gw200105
# Queue the job
queue


