universe = vanilla
executable = /home/kkacanja/ecc_pe/new/gw190425/teob/run.sh
getenv = True
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

output =  /home/kkacanja/ecc_pe/new/gw190425/logs/teob_gw190425.out
error =  /home/kkacanja/ecc_pe/new/gw190425/logs/teob_gw190425.err
log =  /home/kkacanja/ecc_pe/new/gw190425/logs/teob_gw190425.log

# Request resources
request_memory = 70 GB
request_cpus = 64

batch_name = teob_gw190425
# Queue the job
queue


