universe = vanilla
executable = /home/kkacanja/ecc_pe/new/gw200115/seob/run.sh
getenv = True
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

output =  /home/kkacanja/ecc_pe/new/gw200115/logs/seob_gw200115.out
error =  /home/kkacanja/ecc_pe/new/gw200115/logs/seob_gw200115.err
log =  /home/kkacanja/ecc_pe/new/gw200115/logs/seob_gw200115.log

# Request resources
request_memory = 30 GB
request_cpus = 64

batch_name = seob_gw200115
# Queue the job
queue


