universe = vanilla
executable = /home/kkacanja/ecc_pe/gw200105/teob/19ff/run.sh
getenv = True
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

output =  /home/kkacanja/ecc_pe/gw200105/logs/teob_19ff_gw200105.out
error =  /home/kkacanja/ecc_pe/gw200105/logs/teob_19ff_gw200105.err
log =  /home/kkacanja/ecc_pe/gw200105/logs/teob_19ff_gw200105.log

# Request resources
request_memory = 50 GB
request_cpus = 64

batch_name = teob_19ff_gw200105_new_sampling_method
# Queue the job
queue


