universe = vanilla
executable = /home/kkacanja/ecc_pe/new/gw190814/teob/run.sh
getenv = True
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

output =  /home/kkacanja/ecc_pe/new/gw190814/logs/teob_gw190814.out
error =  /home/kkacanja/ecc_pe/new/gw190814/logs/teob_gw190814.err
log =  /home/kkacanja/ecc_pe/new/gw190814/logs/teob_gw190814.log

Requirements = ! regexp("u20node", TARGET.name)

# Request resources
request_memory = 10 GB
request_cpus = 64

batch_name = teob_gw190814
# Queue the job
queue


