universe = vanilla
executable = /home/kkacanja/ecc_pe/gw230529/teobHM/run.sh
getenv = True
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

output =  /home/kkacanja/ecc_pe/gw230529/logs/teobHM_gw230529.out
error =  /home/kkacanja/ecc_pe/gw230529/logs/teobHM_gw230529.err
log =  /home/kkacanja/ecc_pe/gw230529/logs/teobHM_gw230529.log

request_memory = 30 GB
request_cpus = 64

batch_name = teobHM_gw230529

queue


