universe = vanilla
executable = /home/kkacanja/ecc_pe/gw200105/seob/0.3/no_marg/run.sh
getenv = True
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

output =  /home/kkacanja/ecc_pe/gw200105/logs/seob_0.3ecc_gw200105.out
error =  /home/kkacanja/ecc_pe/gw200105/logs/seob_0.3ecc_gw200105.err
log =  /home/kkacanja/ecc_pe/gw200105/logs/seob_0.3ecc_gw200105.log

# Request resources
request_memory = 30 GB
request_cpus = 64

batch_name = seob_0.3ecc_gw200105_nomarg
# Queue the job
queue


