universe = vanilla
executable = /home/kkacanja/ecc_pe/gw200105/teob/30f/run.sh
getenv = True
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

output =  /home/kkacanja/ecc_pe/gw200105/logs/teob_30f_gw200105.out
error =  /home/kkacanja/ecc_pe/gw200105/logs/teob_30f_gw200105.err
log =  /home/kkacanja/ecc_pe/gw200105/logs/teob_30f_gw200105.log

# Request resources
request_memory = 50 GB
request_cpus = 64

batch_name = teob_30f_gw200105
# Queue the job
queue


